### ISSUE TITLE
Запрос на описание возможных desiredCapabilities для данного драйвера

### ISSUE THREAD

**Issue by Goblenus** [lanit-exp/FlaNium.Desktop.Driver#1]
Подскажите пожалуйста, возможно добавить описание возможных desiredCapabilities для данного драйвера?

Нашёл несколько:
* DebugConnectToRunningApp
* App
* Arguments
* LaunchDelay

И дополнительный вопрос, есть ли какие-либо ограничения для использования этого драйвера через Python?

@evkall добавляю для нотификации.

**Comment by cmttwd** [comment]
Capabilities:

app - абсолютный путь до тестируемого приложения;
args - аргументы запуска тестируемого приложения;
debugConnectToRunningApp - подключение к экземпляру ранее запущенного приложения (true/false - по умолчанию);
innerPort - установка порта (по умолчанию 9998);
launchDelay - задержка после запуска приложения в мс (по умолчанию 0).

Ограничений в работе совместно с Python нет.

**Comment by Goblenus** [comment]
@cmttwd может быть закрыто. Добавил #2
