### ISSUE TITLE
Драйвер не может найти приложение

### ISSUE THREAD

**Issue by Vitaliy-Kuldyaev** [lanit-exp/FlaNium.Desktop.Driver#9]
Если приложение называется (например: 'Mvf.TestOffice.FF.Client.exe'), то при создании драйвера, появляется ошибка "Unable to find process with name: Mvf.TestOffice.FF.Client" 

Если в названии приложения нет точек, например: 'TestApp', то запуск происходит успешно.
 
P.S. Ссылка на тестовый проект (.net DevExpress [ссылка](https://github.com/Vitaliy-Kuldyaev/Mvf.TestOffice.FF.Client/tree/main/Mvf.TestOffice.FF.Client/Mvf.TestOffice.FF.Client/bin/Debug))
P.S.S. Некорректно отрабатывает Application.Attach из FlaUI.Core.

**Comment by cmttwd** [comment]
Исправлено в версии 2.0.0-beta
